version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: calorie-tracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: calorietracker
      MONGO_INITDB_ROOT_PASSWORD: tracker123
      MONGO_INITDB_DATABASE: calorietracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - calorie-tracker-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: calorie-tracker-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "9229:9229"
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://calorietracker:tracker123@mongodb:27017/calorietracker?authSource=admin
      SESSION_SECRET: calorie-tracker-docker-secret-key-2024
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - session_data:/app/sessions
    depends_on:
      - mongodb
    networks:
      - calorie-tracker-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: calorie-tracker-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3001
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - calorie-tracker-network

volumes:
  mongodb_data:
  session_data:

networks:
  calorie-tracker-network:
    driver: bridge